version: '3.6'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    image: supabase/gotrue:v2.58.1
    restart: always
    ports:
      - 9999:9999
    environment:
      API_EXTERNAL_URL: http://localhost:9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: supersecretjwt

volumes:
  db:
